live_config_reload = true

[font]
size = 10.0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
